version: '3.1'
services:
  lb-web:
    image: nginx:alpine
    volumes:
      - ./files/lb-web/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - web1
      - web2
  lb-db:
    image: nginx:alpine
    volumes:
      - ./files/lb-db/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 3306:3306
    depends_on:
      - db1
      - db2
  web1:
    image: nginx:alpine
    volumes:
      - ..:/var/www/s4
      - ./files/nginx1/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php1
      - db1      
      - redis-sentinel-1
      - redis-sentinel-2
      - redis-sentinel-3
  php1:
    build:
      context: .
      dockerfile: fpm.Dockerfile
    image: my_php
    volumes:
      - ..:/var/www/s4
  web2:
    image: nginx:alpine
    volumes:
      - ..:/var/www/s4
      - ./files/nginx2/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php2
      - db1
      - redis-sentinel-1
      - redis-sentinel-2
      - redis-sentinel-3
  php2:
    image: my_php
    volumes:
      - ..:/var/www/s4
    depends_on:
      - php1
  redis-server-1:
    build:
      context: .
      dockerfile: redis.Dockerfile
    image: my_redis
    volumes:
      - ./files/redis/data1:/data
  redis-server-2:
    image: my_redis
    volumes:
      - ./files/redis/data2:/data
    command: 
      - slave
    depends_on:
      - redis-server-1
  redis-server-3:
    image: my_redis
    volumes:
      - ./files/redis/data3:/data
    command: 
      - slave
    depends_on:
      - redis-server-1
  redis-sentinel-1:
    image: my_redis
    expose:
      - "26379"
    volumes:
      - nil:/data
    command: 
      - sentinel
    depends_on:
      - redis-server-1
      - redis-server-2
      - redis-server-3
  redis-sentinel-2:
    image: my_redis
    expose:
      - "26379"
    volumes:
      - nil:/data
    command: 
      - sentinel
    depends_on:
      - redis-server-1
      - redis-server-2
      - redis-server-3
  redis-sentinel-3:
    image: my_redis
    expose:
      - "26379"
    volumes:
      - nil:/data
    command: 
      - sentinel
    depends_on:
      - redis-server-1
      - redis-server-2
      - redis-server-3
  db1:
    image: mariadb
    restart: always
    volumes:
      - ./files/db1/replication.cnf:/etc/mysql/conf.d/replication.cnf
      - ./files/db1/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./files/db1/data:/var/lib/mysql
      - ./files/db.bin:/var/lib/mysql/bin
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_passwd
  db2:
    image: mariadb
    restart: always
    volumes:
      - ./files/db2/replication.cnf:/etc/mysql/conf.d/replication.cnf
      - ./files/db2/init.sh:/docker-entrypoint-initdb.d/init.sh
      - ./files/db2/data:/var/lib/mysql
      - ./files/db.bin:/var/lib/mysql/bin
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_passwd
    depends_on:
      - db1
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db1
      - db2
  redisAdmin:
    build:
      context: .
      dockerfile: phpRedisAdmin.Dockerfile
    image: my_redis_admin
    volumes:
      - ./files/phpRedisAdmin/config.inc.php:/var/www/s4/redis_admin/includes/config.inc.php
    ports:
      - 8090:80
    environment:
      REDIS_1_HOST: redis-server-1
      REDIS_1_NAME: RedisServer1
      REDIS_2_HOST: redis-server-2
      REDIS_2_NAME: RedisServer2
      REDIS_3_HOST: redis-server-3
      REDIS_3_NAME: RedisServer3
    depends_on:
      - php1
volumes:
  nil:
