parameters:
    redis_sentinels:
        - '%env(resolve:REDIS_SENTINEL_1)%'
        - '%env(resolve:REDIS_SENTINEL_2)%'
        - '%env(resolve:REDIS_SENTINEL_3)%'
        
    redis_sentinel_options_session:
        replication: 'sentinel'
        service: '%env(resolve:REDIS_GROUP_NAME)%'
        parameters:
            database: 1
            password: '%env(resolve:REDIS_SENTINEL_AUTH_PASSWORD)%'
    redis_sentinel_options_doctrine_query:
        replication: 'sentinel'
        service: '%env(resolve:REDIS_GROUP_NAME)%'
        parameters:
            database: 2
            password: '%env(resolve:REDIS_SENTINEL_AUTH_PASSWORD)%'
    redis_sentinel_options_doctrine_result:
        replication: 'sentinel'
        service: '%env(resolve:REDIS_GROUP_NAME)%'
        parameters:
            database: 3
            password: '%env(resolve:REDIS_SENTINEL_AUTH_PASSWORD)%'
    redis_sentinel_options_doctrine_metadata:
        replication: 'sentinel'
        service: '%env(resolve:REDIS_GROUP_NAME)%'
        parameters:
            database: 4
            password: '%env(resolve:REDIS_SENTINEL_AUTH_PASSWORD)%'
    redis_sentinel_options_for_redis_queue:
        replication: 'sentinel'
        service: '%env(resolve:REDIS_GROUP_NAME)%'
        parameters:
            database: 5
            password: '%env(resolve:REDIS_SENTINEL_AUTH_PASSWORD)%'
    redis_sentinel_options_for_var_cache:
        replication: 'sentinel'
        service: '%env(resolve:REDIS_GROUP_NAME)%'
        parameters:
            database: 15
            password: '%env(resolve:REDIS_SENTINEL_AUTH_PASSWORD)%'
